// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getdownandoutput
double getdownandoutput(int nInt, double strike, double spot, double vol, double r, double expiry, double Barrier, int nReps);
RcppExport SEXP _EuropeOption_getdownandoutput(SEXP nIntSEXP, SEXP strikeSEXP, SEXP spotSEXP, SEXP volSEXP, SEXP rSEXP, SEXP expirySEXP, SEXP BarrierSEXP, SEXP nRepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nInt(nIntSEXP);
    Rcpp::traits::input_parameter< double >::type strike(strikeSEXP);
    Rcpp::traits::input_parameter< double >::type spot(spotSEXP);
    Rcpp::traits::input_parameter< double >::type vol(volSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type expiry(expirySEXP);
    Rcpp::traits::input_parameter< double >::type Barrier(BarrierSEXP);
    Rcpp::traits::input_parameter< int >::type nReps(nRepsSEXP);
    rcpp_result_gen = Rcpp::wrap(getdownandoutput(nInt, strike, spot, vol, r, expiry, Barrier, nReps));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _EuropeOption_rcpp_hello_world();

static const R_CallMethodDef CallEntries[] = {
    {"_EuropeOption_getdownandoutput", (DL_FUNC) &_EuropeOption_getdownandoutput, 8},
    {"_EuropeOption_rcpp_hello_world", (DL_FUNC) &_EuropeOption_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_EuropeOption(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
