# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getdownandoutput <- function(nInt = 20L, strike = 100, spot = 95, vol = 0.2, r = 0.06, expiry = 0.5, Barrier = 93, nReps = 800L) {
    .Call(`_EuropeOption_getdownandoutput`, nInt, strike, spot, vol, r, expiry, Barrier, nReps)
}

